language: ruby
sudo: false
cache: bundler
before_install:
  - gem install bundler:2.0.1
script: travis_wait bundle exec rake generate
after_success:
  - '[ "${TRAVIS_BRANCH}" = "current" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] && bundle exec rake deploy || false'
